package io.jpress.addon.friendlink.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.friendlink.model.base.BaseFriendLink;

/**
 * Generated by JPress.
 */
@Table(tableName = "friend_link", primaryKey = "id")
public class FriendLink extends BaseFriendLink<FriendLink> {

    private static final long serialVersionUID = 1L;

	
}

