package io.jpress.addon.friendlink.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFriendLink<M extends BaseFriendLink<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

	public void setId(java.lang.Long id) {
		set("id", id);
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 链接名
     */
	public void setName(java.lang.String name) {
		set("name", name);
	}

    /**
     * 链接名
     */
	public java.lang.String getName() {
		return getStr("name");
	}

    /**
     * 网址
     */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}

    /**
     * 网址
     */
	public java.lang.String getUrl() {
		return getStr("url");
	}

    /**
     * 图标路径
     */
	public void setIco(java.lang.String ico) {
		set("ico", ico);
	}

    /**
     * 图标路径
     */
	public java.lang.String getIco() {
		return getStr("ico");
	}

    /**
     * 排序
     */
	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}

    /**
     * 排序
     */
	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

    /**
     * 创建时间
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建时间
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

}

