package io.jpress.addon.topic.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.topic.model.base.BaseTopicCatalogue;
import io.jpress.module.article.model.Article;

import java.util.List;

/**
 * Generated by JPress.
 */
@Table(tableName = "topic_catalogue", primaryKey = "id")
public class TopicCatalogue extends BaseTopicCatalogue<TopicCatalogue> {

    private static final long serialVersionUID = 1L;

    private List<Article> articles;

    public List<Article> getArticles() {
        return articles;
    }

    public TopicCatalogue setArticles(List<Article> articles) {
        this.articles = articles;
        return this;
    }
}

