package io.jpress.addon.topic.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.topic.model.base.BaseTopic;

/**
 * Generated by JPress.
 */
@Table(tableName = "topic", primaryKey = "id")
public class Topic extends BaseTopic<Topic> {

    private static final long serialVersionUID = 1L;

	
}

