package io.jpress.addon.topic.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.topic.model.base.BaseTopicCatalogue;

/**
 * Generated by JPress.
 */
@Table(tableName = "topic_catalogue", primaryKey = "id")
public class TopicCatalogue extends BaseTopicCatalogue<TopicCatalogue> {

    private static final long serialVersionUID = 1L;

	
}

