package io.jpress.addon.topic.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTopic<M extends BaseTopic<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    /**
     * 主键ID
     */
	public void setId(java.lang.Long id) {
		set("id", id);
	}

    /**
     * 主键ID
     */
	public java.lang.Long getId() {
		return getLong("id");
	}

    /**
     * 专题名称
     */
	public void setTopicName(java.lang.String topicName) {
		set("topic_name", topicName);
	}

    /**
     * 专题名称
     */
	public java.lang.String getTopicName() {
		return getStr("topic_name");
	}

    /**
     * slug
     */
	public void setSlug(java.lang.String slug) {
		set("slug", slug);
	}

    /**
     * slug
     */
	public java.lang.String getSlug() {
		return getStr("slug");
	}

    /**
     * 专题标识
     */
	public void setTopicCode(java.lang.String topicCode) {
		set("topic_code", topicCode);
	}

    /**
     * 专题标识
     */
	public java.lang.String getTopicCode() {
		return getStr("topic_code");
	}

    /**
     * 内容描述
     */
	public void setTopicContent(java.lang.String topicContent) {
		set("topic_content", topicContent);
	}

    /**
     * 内容描述
     */
	public java.lang.String getTopicContent() {
		return getStr("topic_content");
	}

    /**
     * 摘要
     */
	public void setTopicSummary(java.lang.String topicSummary) {
		set("topic_summary", topicSummary);
	}

    /**
     * 摘要
     */
	public java.lang.String getTopicSummary() {
		return getStr("topic_summary");
	}

    /**
     * 专题类型：0：文章专题;1:资源专题
     */
	public void setTopicType(java.lang.String topicType) {
		set("topic_type", topicType);
	}

    /**
     * 专题类型：0：文章专题;1:资源专题
     */
	public java.lang.String getTopicType() {
		return getStr("topic_type");
	}

    /**
     * 专题项数量
     */
	public void setCount(java.lang.Long count) {
		set("count", count);
	}

    /**
     * 专题项数量
     */
	public java.lang.Long getCount() {
		return getLong("count");
	}

    /**
     * 排序编码
     */
	public void setOrderNumber(java.lang.Integer orderNumber) {
		set("order_number", orderNumber);
	}

    /**
     * 排序编码
     */
	public java.lang.Integer getOrderNumber() {
		return getInt("order_number");
	}

    /**
     * 创建日期
     */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}

    /**
     * 创建日期
     */
	public java.util.Date getCreated() {
		return getDate("created");
	}

    /**
     * 最后更新日期
     */
	public void setModified(java.util.Date modified) {
		set("modified", modified);
	}

    /**
     * 最后更新日期
     */
	public java.util.Date getModified() {
		return getDate("modified");
	}

}

