package io.jpress.addon.message.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseJpressAddonArticleDoc<M extends BaseJpressAddonArticleDoc<M>> extends JbootModel<M> implements IBean {

    private static final long serialVersionUID = 1L;

    public void setId(Long id) {
        set("id", id);
    }

    public Long getId() {
        return getLong("id");
    }

    public void setFirstTitle(String firstTitle) {
        set("first_title", firstTitle);
    }

    public String getFirstTitle() {
        return getStr("first_title");
    }

    public void setSecondTitle(String secondTitle) {
        set("second_title", secondTitle);
    }

    public String getSecondTitle() {
        return getStr("second_title");
    }

    public void setArticleId(String articleId) {
        set("article_id", articleId);
    }

    public String getArticleId() {
        return getStr("article_id");
    }

    public void setArticleTitle(String articleTitle) {
        set("article_title", articleTitle);
    }

    public String getArticleTitle() {
        return getStr("article_title");
    }

    public void setUrl(String url) {
        set("url", url);
    }

    public String getUrl() {
        return getStr("url");
    }

    /**
     * 是否展示
     */
    public void setShow(java.lang.Boolean show) {
        set("show", show);
    }

    /**
     * 是否展示
     */
    public java.lang.Boolean getShow() {
        return get("show");
    }
}
