package io.jpress.addon.message.model;

import io.jboot.db.annotation.Table;
import io.jpress.addon.message.model.base.BaseJpressAddonArticleDoc;

/**
 * Generated by JPress.
 */
@Table(tableName = "jpress_addon_message", primaryKey = "id")
public class JpressAddonArticleDoc extends BaseJpressAddonArticleDoc<JpressAddonArticleDoc> {

    private static final long serialVersionUID = 1L;

	
}
